<?php
$value = array (
  'wwwprefix' => 'http://127.0.0.1:81',
  'imgprefix' => 'http://fangtuanwang.a68.76376.com',
  'cssprefix' => 'http://fangtuanwang.a68.76376.com',
  'sitename' => '房团长',
  'sitetitle' => '在线团房网',
  'abbreviation' => '房团长',
  'couponname' => '优惠券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'invitecredit' => '0',
  'sideteam' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => '',
  'icp' => '陕ICP备11011224号',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'googlemap' => '',
);
?>